// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleMenu.Data;

#nullable disable

namespace SimpleMenu.Migrations
{
    [DbContext(typeof(SimpleMenuDbContext))]
    [Migration("20250227015450_initialDb")]
    partial class initialDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SimpleMenu.Models.DishIngredientModel", b =>
                {
                    b.Property<int>("dishId")
                        .HasColumnType("int");

                    b.Property<int>("ingredientId")
                        .HasColumnType("int");

                    b.HasKey("dishId", "ingredientId");

                    b.HasIndex("ingredientId");

                    b.ToTable("TblDishIngredient");

                    b.HasData(
                        new
                        {
                            dishId = 1,
                            ingredientId = 1
                        },
                        new
                        {
                            dishId = 1,
                            ingredientId = 2
                        },
                        new
                        {
                            dishId = 1,
                            ingredientId = 3
                        });
                });

            modelBuilder.Entity("SimpleMenu.Models.DishModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("imgUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("price")
                        .HasColumnType("double");

                    b.HasKey("id");

                    b.ToTable("TblDish");

                    b.HasData(
                        new
                        {
                            id = 1,
                            imgUrl = "https://i.pinimg.com/736x/6a/88/32/6a8832d29a911b320f9c68af86f8e134.jpg",
                            name = "Pizza",
                            price = 699.0
                        });
                });

            modelBuilder.Entity("SimpleMenu.Models.IngredientModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("TblIngredient");

                    b.HasData(
                        new
                        {
                            id = 1,
                            name = "Tomato Sauce"
                        },
                        new
                        {
                            id = 2,
                            name = " Mozarella Cheese"
                        },
                        new
                        {
                            id = 3,
                            name = "Pepperoni"
                        });
                });

            modelBuilder.Entity("SimpleMenu.Models.DishIngredientModel", b =>
                {
                    b.HasOne("SimpleMenu.Models.DishModel", "Dish")
                        .WithMany("DishIngredient")
                        .HasForeignKey("dishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SimpleMenu.Models.IngredientModel", "Ingredient")
                        .WithMany("DishIngredient")
                        .HasForeignKey("ingredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dish");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("SimpleMenu.Models.DishModel", b =>
                {
                    b.Navigation("DishIngredient");
                });

            modelBuilder.Entity("SimpleMenu.Models.IngredientModel", b =>
                {
                    b.Navigation("DishIngredient");
                });
#pragma warning restore 612, 618
        }
    }
}
